Algoritmo "RepitaAte"

Var
// Seção de Declarações das variáveis 
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Defina o valor de I:")
leia(i)

//       repita
//             escreval("Valor de I:", i)
//             i<- i+1
//       ate   i>10
//escreval("Valor de I:",i)

       repita
             escreval("Valor de I:",i)
             i<- i+1
       ate   i<=1
Escreval("Valor de I:",i)
Fimalgoritmo